version: "3.9"

services:
  flyway:
    image: flyway/flyway:latest
    command: ["migrate", "-connectRetries=60"]
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf/
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BACKUPS_TIMEOUT=${BACKUPS_TIMEOUT}
    ports:
      - "5432:5432"
    volumes:
      - ./roles:/docker-entrypoint-initdb.d/
      - ./backuper:/root/backuper/

  analyzer:
    restart: no
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SSL_MODE=${SSL_MODE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ANALYZER_COUNT=${ANALYZER_COUNT}
      - AMOUNT_OF_DATA=${AMOUNT_OF_DATA}
    volumes:
      - ./analyzer/logs:/root/logs
    depends_on:
      - flyway
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres

volumes:
  data:
  grafana_data: